exclude(:test_include?, "auto_compact is not implemented")
exclude(:test_gc_compact_stress, "auto_compact is not implemented")
exclude(:test_key?, "auto_compact is not implemented")
exclude(:test_member?, "auto_compact is not implemented")
exclude(:test_map, "WeakMap is not properly implemented with MMTk")
exclude(:test_aset_const, "WeakMap is not properly implemented with MMTk")
exclude(:test_inspect, "WeakMap is not properly implemented with MMTk")
exclude(:test_inspect_garbage, "WeakMap is not properly implemented with MMTk")
exclude(:test_delete, "WeakMap is not properly implemented with MMTk")
exclude(:test_each, "WeakMap is not properly implemented with MMTk")
exclude(:test_each_key, "WeakMap is not properly implemented with MMTk")
exclude(:test_each_value, "WeakMap is not properly implemented with MMTk")
exclude(:test_size, "WeakMap is not properly implemented with MMTk")
exclude(:test_length, "WeakMap is not properly implemented with MMTk")
exclude(:test_frozen_object, "WeakMap is not properly implemented with MMTk")
exclude(:test_no_memory_leak, "WeakMap is not properly implemented with MMTk")
exclude(:test_compaction, "WeakMap is not properly implemented with MMTk")
exclude(:test_replaced_values_bug_19531, "WeakMap is not properly implemented with MMTk")
exclude(:test_use_after_free_bug_20688, "WeakMap is not properly implemented with MMTk")
